{
 "title": "VMware Datastore View",
 "description": "Datastore View for vmware-exporter",
 "tags": [
  "vmware",
  "datastore"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "20s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(vmware_vcenter_info{},job)"
    }
   },
   {
    "name": "vcenter",
    "label": "vCenter",
    "query": {
     "query": "label_values(vmware_vcenter_info{job=\"$job\"},vcenter)"
    }
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values(vmware_datacenter_info{vcenter=~\"$vcenter\"},dc)"
    }
   },
   {
    "name": "dcmo",
    "query": {
     "query": "label_values(vmware_datacenter_info{vcenter=~\"$vcenter\", dc=~\"$datacenter\"},dcmo)"
    }
   },
   {
    "name": "dcdsfolder",
    "query": {
     "query": "label_values(vmware_folder_info{vcenter=~\"$vcenter\", dcmo=~\"$dcmo\", dc=\"datastore\"},foldermo)"
    }
   },
   {
    "name": "dchostfolder",
    "query": {
     "query": "label_values(vmware_folder_info{vcenter=~\"$vcenter\", dcmo=~\"$dcmo\", dc=\"host\"},foldermo)"
    }
   },
   {
    "name": "datastore",
    "label": "Datastore",
    "query": {
     "query": "label_values(vmware_datastore_info{vcenter=~\"$vcenter\"},ds)"
    }
   },
   {
    "name": "dsmo",
    "query": {
     "query": "label_values(vmware_datastore_info{vcenter=~\"$vcenter\", ds=~\"$datastore\"},dsmo)"
    }
   },
   { "name": "top", "label": "Top", "query": "5,10,20,30,40,50,100" }
  ]
 },
 "panels": [
  {
   "title": "Datastore Space Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(max by (ds) (\n  (vmware_datastore_capacity{vcenter=~\"$vcenter\", ds=~\"$datastore\"} - vmware_datastore_free{vcenter=~\"$vcenter\", ds=~\"$datastore\"}) / vmware_datastore_capacity{vcenter=~\"$vcenter\", ds=~\"$datastore\"} * 100\n))",
     "legendFormat": "{{ds}}"
    }
   ]
  },
  {
   "title": "Datastore Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(\n  vmware_vm_datastore_totalReadLatency_average{vcenter=~\"$vcenter\"}\n  * on(vm, vcenter) group_left()\n  (count by(vm, vcenter)(vmware_vm_datastore_capacity_used{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}) > 0)\n)",
     "legendFormat": "Read"
    },
    {
     "expr": "avg(\n  vmware_vm_datastore_totalWriteLatency_average{vcenter=~\"$vcenter\"}\n  * on(vm, vcenter) group_left()\n  (count by(vm, vcenter)(vmware_vm_datastore_capacity_used{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}) > 0)\n)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Top $top VMs per Datastore Throughput",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n  sum by (vm) (\n    vmware_vm_datastore_read_average{vcenter=~\"$vcenter\"} + vmware_vm_datastore_write_average{vcenter=~\"$vcenter\"}\n  ) * on (vm) group_left() (count by (vm) (vmware_vm_datastore_capacity_used{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}) > 0)\n)",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Top $top VMs per Datastore IO",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n  sum by (vm) (\n    vmware_vm_datastore_numberReadAveraged_average{vcenter=~\"$vcenter\"} + vmware_vm_datastore_numberWriteAveraged_average{vcenter=~\"$vcenter\"}\n  ) * on (vm) group_left() (count by (vm) (vmware_vm_datastore_capacity_used{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}) > 0)\n)",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Top $top VMs Stored on Disk",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n  max by (vm) (vmware_vm_datastore_capacity_used{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"})\n)",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Datastore Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "sum(\n  vmware_vm_datastore_read_average{vcenter=~\"$vcenter\"}\n  * on(vm,vcenter) group_left()\n  (count by(vm,vcenter)(vmware_vm_datastore_capacity_used{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}) > 0)\n)",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(\n  vmware_vm_datastore_write_average{vcenter=~\"$vcenter\"}\n  * on(vm,vcenter) group_left()\n  (count by(vm,vcenter)(vmware_vm_datastore_capacity_used{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}) > 0)\n) * -1",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Datastore IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(\n  vmware_vm_datastore_numberReadAveraged_average{vcenter=~\"$vcenter\"}\n  * on(vm,vcenter) group_left()\n  (count by(vm,vcenter)(vmware_vm_datastore_capacity_used{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}) > 0)\n)",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(\n  vmware_vm_datastore_numberWriteAveraged_average{vcenter=~\"$vcenter\"}\n  * on(vm,vcenter) group_left()\n  (count by(vm,vcenter)(vmware_vm_datastore_capacity_used{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}) > 0)\n) * -1",
     "legendFormat": "Write"
    }
   ]
  }
 ]
}