{
 "title": "VMware VM View",
 "description": "Virtual Machine View for vmware-exporter",
 "tags": [
  "vmware",
  "vm"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "20s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(vmware_vcenter_info,job)"
    }
   },
   {
    "name": "vcenter",
    "label": "vCenter",
    "query": {
     "query": "label_values(vmware_vcenter_info{job=\"$job\"},vcenter)"
    }
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values(vmware_datacenter_info{vcenter=~\"$vcenter\"},dc)"
    }
   },
   {
    "name": "dcmo",
    "query": {
     "query": "label_values(vmware_datacenter_info{vcenter=~\"$vcenter\", dc=~\"$datacenter\"},dcmo)"
    }
   },
   {
    "name": "dchostfolder",
    "query": {
     "query": "label_values(vmware_folder_info{vcenter=~\"$vcenter\", dcmo=~\"$dcmo\", dc=\"host\"},foldermo)"
    }
   },
   {
    "name": "computemo",
    "query": {
     "query": "label_values(vmware_compute_info{vcenter=~\"$vcenter\", foldermo=~\"$dchostfolder\"}, cmo)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vmware_cluster_info{vcenter=~\"$vcenter\", foldermo=~\"$dchostfolder\"},vmwcluster)"
    }
   },
   {
    "name": "clustermo",
    "query": {
     "query": "label_values(vmware_cluster_info{vcenter=~\"$vcenter\", foldermo=~\"$dchostfolder\", vmwcluster=~\"$cluster\"}, cmo)"
    }
   },
   {
    "name": "esxi_host",
    "label": "ESXi Host",
    "query": {
     "query": "label_values(vmware_host_info{vcenter=~\"$vcenter\", cmo=~\"$computemo|$clustermo\"}, host)"
    }
   },
   {
    "name": "hostmolist",
    "query": {
     "query": "label_values(vmware_host_info{vcenter=~\"$vcenter\", cmo=~\"$computemo|$clustermo\", host=~\"$esxi_host\"}, hostmo)"
    }
   },
   {
    "name": "vm",
    "label": "VirtualMachine",
    "query": {
     "query": "label_values(vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmolist\"}, vm)"
    }
   },
   {
    "name": "vmmo",
    "query": {
     "query": "label_values(vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmolist\", vm=~\"$vm\"}, vmmo)"
    }
   },
   {
    "name": "hostmo",
    "query": {
     "query": "label_values(vmware_vm_info{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\", vm=~\"$vm\"}, hostmo)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "vCPUs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_cpu_corecount{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"}",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} / \n(\n  scalar(vmware_host_cpu_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}) *\n  scalar(vmware_vm_cpu_corecount{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"})\n) \n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scalar(\n    vmware_vm_mem_active_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"}\n) / \n(\n    vmware_vm_mem_capacity{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} * 1024\n)\n* 100\n",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} * 1000 * 1000",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "CPU Pressure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_cpu_demand_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} / \nvmware_vm_cpu_entitlement_latest{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"}",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "CPU Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_cpu_latency_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} / 100 ",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Data on Disk",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_datastore_capacity_used{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"}",
     "legendFormat": "vCenter"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{job=\"node\", host=~\"$vm\", fstype!~\"tmpfs|overlay|devtmpfs|nfs4?|cifs|fuse.*|squashfs\"} - node_filesystem_avail_bytes{job=\"node\", host=~\"$vm\", fstype!~\"tmpfs|overlay|devtmpfs|nfs4?|cifs|fuse.*|squashfs\"})",
     "legendFormat": "OS"
    },
    {
     "expr": "sum(windows_logical_disk_size_bytes{job=\"windows\", host=~\"$vm\", volume!~\"HarddiskVolume.*|_Total\"} - windows_logical_disk_free_bytes{job=\"windows\", host=~\"$vm\", volume!~\"HarddiskVolume.*|_Total\"})",
     "legendFormat": "OS"
    }
   ]
  },
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}  ",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "vMemory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_capacity{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"}",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Active Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_active_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"}",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"node\", host=~\"$vm\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "time() - windows_system_system_up_time{job=\"windows\", host=~\"$vm\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "(time() - vmware_vm_boot_timestamp_seconds{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"})\nunless on()\n(up{job=\"node\", host=~\"$vm\"} == 1)\nunless on()\n(up{job=\"windows\", host=~\"$vm\"} == 1)",
     "legendFormat": "vCenter"
    }
   ]
  },
  {
   "title": "Exporter Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node\", host=~\"$vm\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "up{job=\"windows\", host=~\"$vm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Backup",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vcenter_vm_last_backup_timestamp{vm_name=~\"$vm\"} * 1000"
    }
   ]
  },
  {
   "title": "Problem Services / Daemons",
   "type": "table",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "windows_service_state{job=\"windows\", host=~\"$vm\", state=\"stopped\", start_mode=\"auto\"} == 1"
    },
    {
     "expr": "node_systemd_unit_state{job=\"node\", host=~\"$vm\", state=\"failed\"} == 1"
    }
   ]
  },
  { "title": "CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU Usage & Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vmware_vm_cpu_latency_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} / 100",
     "legendFormat": "Latency"
    },
    {
     "expr": "(\n    scalar(\n        vmware_vm_cpu_ready_summation{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} \n    ) / (20 * 1000)\n) /\nvmware_vm_cpu_corecount{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} * 100",
     "legendFormat": "Ready"
    },
    {
     "expr": "(\n    vmware_vm_cpu_costop_summation{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} \n    / (20 * 1000)\n) * 100",
     "legendFormat": "Costop"
    },
    {
     "expr": "node_load1{job=\"node\", host=~\"$vm\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{job=\"node\", host=~\"$vm\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{job=\"node\", host=~\"$vm\"}",
     "legendFormat": "Load 15m"
    },
    {
     "expr": "windows_system_processor_queue_length{job=\"windows\", host=~\"$vm\"}",
     "legendFormat": "Load Queue"
    },
    {
     "expr": "avg by(mode)(rate(node_cpu_seconds_total{job=\"node\", host=~\"\", mode!~\"idle\"}[5m])) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "avg by(mode)(rate(windows_cpu_time_total{job=\"windows\", host=~\"\", mode!~\"idle\"}[5m])) * 100",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} /\n(\n  scalar(vmware_host_cpu_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}) *\n  scalar(vmware_vm_cpu_corecount{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"})\n) * 100",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory - OS Breakdown vs vCenter Active",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\", host=~\"$vm\"} - node_memory_MemFree_bytes{job=\"node\", host=~\"$vm\"} - node_memory_Buffers_bytes{job=\"node\", host=~\"$vm\"} - node_memory_Cached_bytes{job=\"node\", host=~\"$vm\"} - node_memory_SReclaimable_bytes{job=\"node\", host=~\"$vm\"} + node_memory_Shmem_bytes{job=\"node\", host=~\"$vm\"}",
     "legendFormat": "Used by apps"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node\", host=~\"$vm\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node\", host=~\"$vm\"} + node_memory_SReclaimable_bytes{job=\"node\", host=~\"$vm\"} - node_memory_Shmem_bytes{job=\"node\", host=~\"$vm\"}",
     "legendFormat": "Page cache"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"node\", host=~\"$vm\"} - node_memory_SwapFree_bytes{job=\"node\", host=~\"$vm\"}",
     "legendFormat": "Swap used"
    },
    {
     "expr": "vmware_vm_mem_active_average{vcenter=~\"$vcenter\", vmmo=~\"$vmmo\"} * 1024",
     "legendFormat": "vCenter: Active"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\", host=~\"$vm\"}",
     "legendFormat": "Total RAM"
    },
    {
     "expr": "windows_os_visible_memory_bytes{job=\"windows\", host=~\"$vm\"} - windows_memory_available_bytes{job=\"windows\", host=~\"$vm\"}",
     "legendFormat": "Used by apps"
    },
    {
     "expr": "windows_os_visible_memory_bytes{job=\"windows\", host=~\"$vm\"}",
     "legendFormat": "Total RAM"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"node\", host=~\"$vm\"}",
     "legendFormat": "Swap Total"
    },
    {
     "expr": "windows_os_paging_limit_bytes{job=\"windows\", host=~\"$vm\"} - windows_os_paging_free_bytes{job=\"windows\", host=~\"$vm\"}",
     "legendFormat": "Pagefile Used"
    },
    {
     "expr": "windows_os_paging_limit_bytes{job=\"windows\", host=~\"$vm\"}",
     "legendFormat": "Pagefile Total"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Filesystem Disk Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_filesystem_avail_bytes{job=\"node\", host=~\"$vm\", fstype!~\"tmpfs|overlay|devtmpfs|nfs4?|cifs|fuse.*|squashfs\"} / node_filesystem_size_bytes{job=\"node\", host=~\"$vm\", fstype!~\"tmpfs|overlay|devtmpfs|nfs4?|cifs|fuse.*|squashfs\"})) * 100",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "(1 - (windows_logical_disk_free_bytes{job=\"windows\", host=~\"$vm\", volume!~\"HarddiskVolume.*|_Total\"} / windows_logical_disk_size_bytes{job=\"windows\", host=~\"$vm\", volume!~\"HarddiskVolume.*|_Total\"})) * 100",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Local Filesystems",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(1 - (node_filesystem_avail_bytes{job=\"node\", host=~\"$vm\", fstype!~\"tmpfs|overlay|devtmpfs|nfs4?|cifs|fuse.*|squashfs\"} / node_filesystem_size_bytes{job=\"node\", host=~\"$vm\", fstype!~\"tmpfs|overlay|devtmpfs|nfs4?|cifs|fuse.*|squashfs\"})) * 100\nor label_replace(\n  (1 - (windows_logical_disk_free_bytes{job=\"windows\", host=~\"$vm\", volume!~\"HarddiskVolume.*|_Total\"} / windows_logical_disk_size_bytes{job=\"windows\", host=~\"$vm\", volume!~\"HarddiskVolume.*|_Total\"})) * 100,\n  \"mountpoint\", \"$1\", \"volume\", \"(.+)\"\n)"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"node\", host=~\"$vm\", fstype!~\"tmpfs|overlay|devtmpfs|nfs4?|cifs|fuse.*|squashfs\"} - node_filesystem_avail_bytes{job=\"node\", host=~\"$vm\", fstype!~\"tmpfs|overlay|devtmpfs|nfs4?|cifs|fuse.*|squashfs\"}\nor label_replace(\n  windows_logical_disk_size_bytes{job=\"windows\", host=~\"$vm\", volume!~\"HarddiskVolume.*|_Total\"} - windows_logical_disk_free_bytes{job=\"windows\", host=~\"$vm\", volume!~\"HarddiskVolume.*|_Total\"},\n  \"mountpoint\", \"$1\", \"volume\", \"(.+)\"\n)"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"node\", host=~\"$vm\", fstype!~\"tmpfs|overlay|devtmpfs|nfs4?|cifs|fuse.*|squashfs\"}\nor label_replace(\n  windows_logical_disk_size_bytes{job=\"windows\", host=~\"$vm\", volume!~\"HarddiskVolume.*|_Total\"},\n  \"mountpoint\", \"$1\", \"volume\", \"(.+)\"\n)"
    }
   ]
  },
  {
   "title": "Remote Mounts",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(1 - (node_filesystem_avail_bytes{job=\"node\", host=~\"$vm\", fstype=~\"nfs4?|cifs|fuse.*\"} / node_filesystem_size_bytes{job=\"node\", host=~\"$vm\", fstype=~\"nfs4?|cifs|fuse.*\"})) * 100"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"node\", host=~\"$vm\", fstype=~\"nfs4?|cifs|fuse.*\"} - node_filesystem_avail_bytes{job=\"node\", host=~\"$vm\", fstype=~\"nfs4?|cifs|fuse.*\"}"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"node\", host=~\"$vm\", fstype=~\"nfs4?|cifs|fuse.*\"}"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{job=\"node\", host=~\"$vm\", device!~\"dm-.*|loop.*\"}[5m]) / rate(node_disk_reads_completed_total{job=\"node\", host=~\"$vm\", device!~\"dm-.*|loop.*\"}[5m]) * 1000",
     "legendFormat": "read: {{device}}"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{job=\"node\", host=~\"$vm\", device!~\"dm-.*|loop.*\"}[5m]) / rate(node_disk_writes_completed_total{job=\"node\", host=~\"$vm\", device!~\"dm-.*|loop.*\"}[5m]) * 1000 * -1",
     "legendFormat": "write: {{device}}"
    },
    {
     "expr": "rate(windows_logical_disk_read_latency_seconds_total{job=\"windows\", host=~\"$vm\", volume!~\"HarddiskVolume.*|_Total\"}[5m]) / rate(windows_logical_disk_reads_total{job=\"windows\", host=~\"$vm\", volume!~\"HarddiskVolume.*|_Total\"}[5m]) * 1000",
     "legendFormat": "read: {{volume}}"
    },
    {
     "expr": "rate(windows_logical_disk_write_latency_seconds_total{job=\"windows\", host=~\"$vm\", volume!~\"HarddiskVolume.*|_Total\"}[5m]) / rate(windows_logical_disk_writes_total{job=\"windows\", host=~\"$vm\", volume!~\"HarddiskVolume.*|_Total\"}[5m]) * 1000 * -1",
     "legendFormat": "write: {{volume}}"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"node\", host=~\"$vm\", device!~\"dm-.*|loop.*\"}[5m])",
     "legendFormat": "read: {{device}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"node\", host=~\"$vm\", device!~\"dm-.*|loop.*\"}[5m]) * -1",
     "legendFormat": "write: {{device}}"
    },
    {
     "expr": "rate(windows_logical_disk_read_bytes_total{job=\"windows\", host=~\"$vm\", volume!~\"HarddiskVolume.*|_Total\"}[5m])",
     "legendFormat": "read: {{volume}}"
    },
    {
     "expr": "rate(windows_logical_disk_write_bytes_total{job=\"windows\", host=~\"$vm\", volume!~\"HarddiskVolume.*|_Total\"}[5m]) * -1",
     "legendFormat": "write: {{volume}}"
    }
   ]
  },
  {
   "title": "Disk Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{job=\"node\", host=~\"$vm\", device!~\"dm-.*|loop.*\"}[5m])",
     "legendFormat": "read: {{device}}"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{job=\"node\", host=~\"$vm\", device!~\"dm-.*|loop.*\"}[5m]) * -1",
     "legendFormat": "write: {{device}}"
    },
    {
     "expr": "rate(windows_logical_disk_reads_total{job=\"windows\", host=~\"$vm\", volume!~\"HarddiskVolume.*|_Total\"}[5m])",
     "legendFormat": "read: {{volume}}"
    },
    {
     "expr": "rate(windows_logical_disk_writes_total{job=\"windows\", host=~\"$vm\", volume!~\"HarddiskVolume.*|_Total\"}[5m]) * -1",
     "legendFormat": "write: {{volume}}"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Network Errors & Drops",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total{job=\"node\", host=~\"$vm\", device!~\"lo|veth.*|docker.*|br-.*\"}[5m])",
     "legendFormat": "rx errors: {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_errs_total{job=\"node\", host=~\"$vm\", device!~\"lo|veth.*|docker.*|br-.*\"}[5m]) * -1",
     "legendFormat": "tx errors: {{device}}"
    },
    {
     "expr": "rate(node_network_receive_drop_total{job=\"node\", host=~\"$vm\", device!~\"lo|veth.*|docker.*|br-.*\"}[5m])",
     "legendFormat": "rx drops: {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_drop_total{job=\"node\", host=~\"$vm\", device!~\"lo|veth.*|docker.*|br-.*\"}[5m]) * -1",
     "legendFormat": "tx drops: {{device}}"
    },
    {
     "expr": "rate(windows_net_packets_received_errors_total{job=\"windows\", host=~\"$vm\", nic!~\".*isatap.*|.*Loopback.*\"}[5m])",
     "legendFormat": "rx errors: {{nic}}"
    },
    {
     "expr": "rate(windows_net_packets_outbound_errors_total{job=\"windows\", host=~\"$vm\", nic!~\".*isatap.*|.*Loopback.*\"}[5m]) * -1",
     "legendFormat": "tx errors: {{nic}}"
    },
    {
     "expr": "rate(windows_net_packets_received_discarded_total{job=\"windows\", host=~\"$vm\", nic!~\".*isatap.*|.*Loopback.*\"}[5m])",
     "legendFormat": "rx drops: {{nic}}"
    },
    {
     "expr": "rate(windows_net_packets_outbound_discarded_total{job=\"windows\", host=~\"$vm\", nic!~\".*isatap.*|.*Loopback.*\"}[5m]) * -1",
     "legendFormat": "tx drops: {{nic}}"
    }
   ]
  },
  {
   "title": "OS Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node\", host=~\"$vm\", device!~\"lo|veth.*|docker.*|br-.*\"}[5m])",
     "legendFormat": "rx: {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node\", host=~\"$vm\", device!~\"lo|veth.*|docker.*|br-.*\"}[5m]) * -1",
     "legendFormat": "tx: {{device}}"
    },
    {
     "expr": "rate(windows_net_bytes_received_total{job=\"windows\", host=~\"$vm\", nic!~\".*isatap.*|.*Loopback.*|.*Teredo.*\"}[5m])",
     "legendFormat": "rx: {{nic}}"
    },
    {
     "expr": "rate(windows_net_bytes_sent_total{job=\"windows\", host=~\"$vm\", nic!~\".*isatap.*|.*Loopback.*|.*Teredo.*\"}[5m]) * -1",
     "legendFormat": "tx: {{nic}}"
    }
   ]
  }
 ]
}