{
 "title": "VMware Host View",
 "description": "Host View for vmware-exporter",
 "tags": [
  "vmware",
  "esxi"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "20s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(vmware_vcenter_info,job)"
    }
   },
   {
    "name": "vcenter",
    "label": "vCenter",
    "query": {
     "query": "label_values(vmware_vcenter_info{job=\"$job\"},vcenter)"
    }
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values(vmware_datacenter_info{vcenter=~\"$vcenter\"},dc)"
    }
   },
   {
    "name": "dcmo",
    "query": {
     "query": "label_values(vmware_datacenter_info{vcenter=~\"$vcenter\", dc=~\"$datacenter\"},dcmo)"
    }
   },
   {
    "name": "dchostfolder",
    "query": {
     "query": "label_values(vmware_folder_info{vcenter=~\"$vcenter\", dcmo=~\"$dcmo\", dc=\"host\"},foldermo)"
    }
   },
   {
    "name": "computemo",
    "query": {
     "query": "label_values(vmware_compute_info{vcenter=~\"$vcenter\", foldermo=~\"$dchostfolder\"}, cmo)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vmware_cluster_info{vcenter=~\"$vcenter\", foldermo=~\"$dchostfolder\"},vmwcluster)"
    }
   },
   {
    "name": "clustermo",
    "query": {
     "query": "label_values(vmware_cluster_info{vcenter=~\"$vcenter\", foldermo=~\"$dchostfolder\", vmwcluster=~\"$cluster\"}, cmo)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(vmware_host_info{vcenter=~\"$vcenter\"}, host)"
    }
   },
   {
    "name": "hostmo",
    "query": {
     "query": "label_values(vmware_host_info{vcenter=~\"$vcenter\", host=~\"$host\"}, hostmo)"
    }
   },
   {
    "name": "datastore",
    "label": "Datastore",
    "query": {
     "query": "label_values(vmware_datastore_info{vcenter=~\"$vcenter\"},ds)"
    }
   },
   {
    "name": "dsmo",
    "query": {
     "query": "label_values(vmware_host_datastore_accessible{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", ds=~\"$datastore\"},dsmo)"
    }
   },
   { "name": "top", "label": "Top", "query": "5,10,20,30,40,50,100" }
  ]
 },
 "panels": [
  {
   "title": "CPU Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_cpu_usagemhz_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} / \n(\n  scalar(vmware_host_cpu_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}) *\n  scalar(vmware_host_cpu_corecount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"})\n) \n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top VMs per CPU Used",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n    vmware_vm_cpu_usagemhz_average{vcenter=~\"$vcenter\"} * on (vmmo) group_left \n    vmware_vm_info{vcenter=~\"$vcenter\", hostmo=\"$hostmo\"}\n) * 1000 * 1000",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Top VMs per Memory Used",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n    vmware_vm_mem_consumed_average{vcenter=~\"$vcenter\"} * on (vmmo) group_left \n    vmware_vm_info{vcenter=~\"$vcenter\", hostmo=\"$hostmo\"}\n)",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Server",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(\n  label_replace(\n    vmware_host_hardware_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"},\n    \"vendor\", \"$1\", \"vendor\", \"(.*) .*\"\n  ),\n  \"newmodel\", \" \",\"vendor\", \"model\"\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Core Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_cpu_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * 1000 * 1000",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Processor",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\n  vmware_host_hardware_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}, \"cpu_type\", \"$1 $3 $5\", \"cpu_type\", \"(.*)(\\\\(R\\\\))(.*)(\\\\(R\\\\))(.*) CPU @.*\"\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_mem_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} ",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "OS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(\n  vmware_host_software_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"},\n  \"os\",\" \",\"software\",\"version\"\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(vmware_host_mem_consumed_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * 1024) / \nvmware_host_mem_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_software_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_sys_uptime_latest{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}  ",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vmware_host_cpu_usagemhz_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} / \n(\n  scalar(vmware_host_cpu_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}) *\n  scalar(vmware_host_cpu_corecount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"})\n) \n* 100",
     "legendFormat": "Usage"
    },
    {
     "expr": "vmware_host_cpu_latency_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} / 100",
     "legendFormat": "Latency"
    },
    {
     "expr": "(vmware_host_cpu_ready_summation{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} / (20 * 1000)) /\nvmware_host_cpu_corecount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * 100",
     "legendFormat": "Ready"
    },
    {
     "expr": "(vmware_host_cpu_costop_summation{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} / (20 * 1000)) * 100",
     "legendFormat": "Costop"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(vmware_host_mem_consumed_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * 1024) / \n(vmware_host_mem_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"})\n* 100",
     "legendFormat": "Consumed"
    },
    {
     "expr": "(vmware_host_mem_active_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * 1024) / \n(vmware_host_mem_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"})\n* 100",
     "legendFormat": "Active"
    },
    {
     "expr": "(vmware_host_mem_shared_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * 1024)/ \n(vmware_host_mem_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"})\n* 100",
     "legendFormat": "Shared"
    },
    {
     "expr": "(vmware_host_mem_vmmemctl_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * 1024)/ \n(vmware_host_mem_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"})\n* 100",
     "legendFormat": "Ballooned"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "vmware_host_net_bytesRx_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", pfinstance!~\"^vusb.*\"} * 8192",
     "legendFormat": "rx: {{pfinstance}} "
    },
    {
     "expr": "vmware_host_net_bytesTx_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", pfinstance!~\"^vusb.*\"} * -8192",
     "legendFormat": "tx: {{pfinstance}}"
    }
   ]
  },
  {
   "title": "Network Errors and Drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vmware_host_net_errorsRx_summation{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", pfinstance!~\"^vusb.*\"} * 8192",
     "legendFormat": "errors rx: {{pfinstance}} "
    },
    {
     "expr": "vmware_host_net_errorsTx_summation{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", pfinstance!~\"^vusb.*\"} * -8192",
     "legendFormat": "errors tx: {{pfinstance}}"
    },
    {
     "expr": "vmware_host_net_droppedRx_summation{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", pfinstance!~\"^vusb.*\"} * 8192",
     "legendFormat": "dropped rx: {{pfinstance}} "
    },
    {
     "expr": "vmware_host_net_droppedTx_summation{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", pfinstance!~\"^vusb.*\"} * -8192",
     "legendFormat": "dropped tx: {{pfinstance}}"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vmware_vm_datastore_totalReadLatency_average{vcenter=~\"$vcenter\"}\n* on(vm) group_left()\n(\n  count by(vm) (\n    vmware_vm_datastore_capacity_used{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}\n    * on(vm) group_left()\n    vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n  ) > 0\n)",
     "legendFormat": "read: {{vm}} "
    },
    {
     "expr": "vmware_vm_datastore_totalWriteLatency_average{vcenter=~\"$vcenter\"}\n* on(vm) group_left()\n(\n  count by(vm) (\n    vmware_vm_datastore_capacity_used{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}\n    * on(vm) group_left()\n    vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n  ) > 0\n) * -1",
     "legendFormat": "write: {{vm}}"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "vmware_vm_datastore_read_average{vcenter=~\"$vcenter\"}\n* on(vm) group_left()\n(\n  count by(vm) (\n    vmware_vm_datastore_capacity_used{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}\n    * on(vm) group_left()\n    vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n  ) > 0\n)",
     "legendFormat": "read: {{vm}} "
    },
    {
     "expr": "vmware_vm_datastore_write_average{vcenter=~\"$vcenter\"}\n* on(vm) group_left()\n(\n  count by(vm) (\n    vmware_vm_datastore_capacity_used{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}\n    * on(vm) group_left()\n    vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n  ) > 0\n) * -1",
     "legendFormat": "write: {{vm}}"
    }
   ]
  },
  {
   "title": "Disk Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "vmware_vm_datastore_numberReadAveraged_average{vcenter=~\"$vcenter\"}\n* on(vm) group_left()\n(\n  count by(vm) (\n    vmware_vm_datastore_capacity_used{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}\n    * on(vm) group_left()\n    vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n  ) > 0\n)",
     "legendFormat": "read: {{vm}} "
    },
    {
     "expr": "vmware_vm_datastore_numberWriteAveraged_average{vcenter=~\"$vcenter\"}\n* on(vm) group_left()\n(\n  count by(vm) (\n    vmware_vm_datastore_capacity_used{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}\n    * on(vm) group_left()\n    vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n  ) > 0\n) * -1",
     "legendFormat": "write: {{vm}}"
    }
   ]
  },
  {
   "title": "Datastore Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(\n  (\n    vmware_datastore_capacity{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"} - vmware_datastore_free{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"}\n  ) / vmware_datastore_capacity{vcenter=~\"$vcenter\", dsmo=~\"$dsmo\"} * 100\n)",
     "legendFormat": "{{ds}}"
    }
   ]
  },
  {
   "title": "Cores, Threads & vCPUs",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_cpu_corecount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}",
     "legendFormat": "Physical Cores"
    },
    {
     "expr": "vmware_host_cpu_threadcount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}",
     "legendFormat": "Threads (HT)"
    },
    {
     "expr": "sum(\n  vmware_vm_cpu_corecount{vcenter=~\"$vcenter\"}\n  * on(vmmo) group_left\n  vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n)",
     "legendFormat": "vCPUs Allocated"
    }
   ]
  },
  {
   "title": "VMs on this Host",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware_vm_cpu_corecount{vcenter=~\"$vcenter\"} * on(vmmo) group_left(vm) vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "vmware_vm_mem_capacity{vcenter=~\"$vcenter\"} * on(vmmo) group_left(vm) vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 VMs - CPU Latency",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5,\n  vmware_vm_cpu_latency_average{vcenter=~\"$vcenter\"}\n  * on(vmmo) group_left(vm)\n  vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n) / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 VMs - CPU Ready",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5,\n  vmware_vm_cpu_ready_summation{vcenter=~\"$vcenter\"}\n  * on(vmmo) group_left(vm)\n  vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n) / (20 * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VMs with Snapshots > 1 Day",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  (\n    (time() - vmware_vm_snapshot_timestamp_seconds{vcenter=~\"$vcenter\"}) / 86400\n    * on(vmmo) group_left()\n    vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n  ) > 1\n) or vector(0)"
    }
   ]
  },
  {
   "title": "VM Snapshots > 1 Day",
   "type": "table",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n  (time() - vmware_vm_snapshot_timestamp_seconds{vcenter=~\"$vcenter\"}) / 86400\n  * on(vmmo) group_left()\n  vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n) > 1",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}