{
 "title": "VMware Cluster View",
 "description": "Cluster View for vmware-exporter",
 "tags": [
  "vmware",
  "cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "20s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(vmware_vcenter_info,job)"
    }
   },
   {
    "name": "vcenter",
    "label": "vCenter",
    "query": {
     "query": "label_values(vmware_vcenter_info{job=\"$job\"},vcenter)"
    }
   },
   {
    "name": "datacenter",
    "label": "Datacenter",
    "query": {
     "query": "label_values(vmware_datacenter_info{vcenter=~\"$vcenter\"},dc)"
    }
   },
   {
    "name": "dcmo",
    "query": {
     "query": "label_values(vmware_datacenter_info{vcenter=~\"$vcenter\", dc=~\"$datacenter\"},dcmo)"
    }
   },
   {
    "name": "dchostfolder",
    "query": {
     "query": "label_values(vmware_folder_info{vcenter=~\"$vcenter\", dcmo=~\"$dcmo\", dc=\"host\"},foldermo)"
    }
   },
   {
    "name": "computemo",
    "query": {
     "query": "label_values(vmware_compute_info{vcenter=~\"$vcenter\", foldermo=~\"$dchostfolder\"}, cmo)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(vmware_cluster_info{vcenter=~\"$vcenter\", foldermo=~\"$dchostfolder\"},vmwcluster)"
    }
   },
   {
    "name": "clustermo",
    "query": {
     "query": "label_values(vmware_cluster_info{vcenter=~\"$vcenter\", foldermo=~\"$dchostfolder\", vmwcluster=~\"$cluster\"}, cmo)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(vmware_host_info{vcenter=~\"$vcenter\", cmo=~\"$computemo|$clustermo\"}, host)"
    }
   },
   {
    "name": "hostmo",
    "query": {
     "query": "label_values(vmware_host_info{vcenter=~\"$vcenter\", cmo=~\"$computemo|$clustermo\", host=~\"$host\"}, hostmo)"
    }
   },
   { "name": "top", "label": "Top", "query": "5,10,20,30,40,50,100" }
  ]
 },
 "panels": [
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_host_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Cores & Threads",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_host_cpu_corecount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"})",
     "legendFormat": "Cores"
    },
    {
     "expr": "sum(vmware_host_cpu_threadcount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"})",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    vmware_host_mem_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Running VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  vmware_host_cpu_usagemhz_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n) /\nsum(\n  vmware_host_cpu_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * \n  vmware_host_cpu_corecount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n) \n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmware_host_mem_consumed_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * 1024) / \nsum(vmware_host_mem_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"})\n* 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Overcommit",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  vmware_vm_cpu_corecount{vcenter=~\"$vcenter\"} * on (vmmo) group_left \n  vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n)\n/ \nsum(vmware_host_cpu_threadcount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Available",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    vmware_host_cpu_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} *\n    vmware_host_cpu_corecount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * \n    1000 * 1000\n) - \nsum(\n    vmware_host_cpu_usagemhz_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * 1000 * 1000\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Compute Capacity",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    vmware_host_cpu_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} *\n    vmware_host_cpu_corecount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * \n    1000 * 1000\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory GB per Core",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    vmware_vm_mem_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n) / \nsum(\n   vmware_host_cpu_corecount{ vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    vmware_host_mem_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n) - \nsum(\n    vmware_host_mem_consumed_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * 1024\n)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Top VMs per CPU Used",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n    vmware_vm_cpu_usagemhz_average{vcenter=~\"$vcenter\"} * on (vmmo) group_left \n    vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n) * 1000 * 1000",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Top VMs per Memory Used",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n    vmware_vm_mem_consumed_average{vcenter=~\"$vcenter\"} * on (vmmo) group_left \n    vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n)",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  vmware_host_cpu_usagemhz_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n) / \nsum(\n  vmware_host_cpu_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} *\n  vmware_host_cpu_corecount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n) \n* 100",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(\n    vmware_host_cpu_latency_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n) / 100",
     "legendFormat": "Latency"
    },
    {
     "expr": "avg(\n    sum(\n        vmware_host_cpu_ready_summation{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} / (20 * 1000)\n    ) /\n    sum(\n        vmware_host_cpu_corecount{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n    ) \n)\n* 100",
     "legendFormat": "Ready"
    },
    {
     "expr": "avg(\n    vmware_host_cpu_costop_summation{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} / (20 * 1000)\n) \n* 100",
     "legendFormat": "Costop"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n    vmware_host_mem_consumed_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * 1024\n) / \nsum(\n    vmware_host_mem_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n)\n* 100",
     "legendFormat": "Consumed"
    },
    {
     "expr": "sum(\n    vmware_host_mem_active_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * 1024\n) / \nsum(\n    vmware_host_mem_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n)\n* 100",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(\n    vmware_host_mem_shared_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * 1024\n)/ \nsum(\n    vmware_host_mem_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n)\n* 100",
     "legendFormat": "Shared"
    },
    {
     "expr": "sum(\n    vmware_host_mem_vmmemctl_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * 1024\n)/ \nsum(\n    vmware_host_mem_capacity{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n)\n* 100",
     "legendFormat": "Ballooned"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(vmware_host_net_bytesRx_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", pfinstance!~\"^vusb.*\"} * 8192)",
     "legendFormat": "rx: {{pfinstance}} "
    },
    {
     "expr": "sum(vmware_host_net_bytesTx_average{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\", pfinstance!~\"^vusb.*\"} * -8192)",
     "legendFormat": "tx: {{pfinstance}}"
    }
   ]
  },
  {
   "title": "Top VMs per Network Receive",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n    sum(vmware_vm_net_bytesRx_average{vcenter=~\"$vcenter\", pfinstance!~\"^vmnic.*|^vusb.*\"}) by (vm) * on (vm) group_left\n    vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * 8192\n)",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Top VMs per Network Transmit",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n    sum(vmware_vm_net_bytesTx_average{vcenter=~\"$vcenter\", pfinstance!~\"^vmnic.*|^vusb.*\"}) by (vm) * on (vm) group_left\n    vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"} * 8192\n)",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "vCPUs Allocated",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  vmware_vm_cpu_corecount{vcenter=~\"$vcenter\"}\n  * on(vmmo) group_left\n  vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n)"
    }
   ]
  },
  {
   "title": "Top $top VMs - CPU Latency",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($top,\n  vmware_vm_cpu_latency_average{vcenter=~\"$vcenter\"}\n  * on(vmmo) group_left(vm)\n  vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n) / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top $top VMs - CPU Ready",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk($top,\n  vmware_vm_cpu_ready_summation{vcenter=~\"$vcenter\"}\n  * on(vmmo) group_left(vm)\n  vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n) / (20 * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VMs with Snapshots > 1 Day",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  (\n    (time() - vmware_vm_snapshot_timestamp_seconds{vcenter=~\"$vcenter\"}) / 86400\n    * on(vmmo) group_left()\n    vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n  ) > 1\n) or vector(0)"
    }
   ]
  },
  {
   "title": "VM Snapshots > 1 Day",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n  (time() - vmware_vm_snapshot_timestamp_seconds{vcenter=~\"$vcenter\"}) / 86400\n  * on(vmmo) group_left(host)\n  vmware_vm_info{vcenter=~\"$vcenter\", hostmo=~\"$hostmo\"}\n) > 1",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}